# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_on_date',
        ),
    ]
